WITH ECOLI_RANK AS(
    SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK
    FROM ECOLI_DATA
)

SELECT ID,
CASE 
    WHEN 0 <= SIZE_RANK AND SIZE_RANK <= 0.25 THEN "CRITICAL"
    WHEN 0.25 < SIZE_RANK AND SIZE_RANK <= 0.5  THEN "HIGH"
    WHEN 0.50 < SIZE_RANK AND SIZE_RANK <= 0.75  THEN "MEDIUM"
    WHEN 0.75 < SIZE_RANK AND SIZE_RANK <= 1 THEN "LOW"
END AS COLONY_NAME
FROM ECOLI_RANK
ORDER BY ID