SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID in (
    select ITEM_ID
    from ITEM_INFO
    where RARITY = 'RARE'
    )
ORDER BY 1 DESC